linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - unused

run:
  timeout: 5m
  concurrency: 4
  tests: true

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - tmp
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - text: "could not import sync/atomic"
      linters:
        - typecheck
    - text: "unsupported version: 2"
      linters:
        - typecheck
    - text: "could not load export data: internal error in importing"
      linters:
        - goanalysis_metalinter

output:
  sort-results: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: "github.com/theblitlabs/parity-runner"